/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _AnalyzeRoute } from '../pages/analyze';
import { Route as _IndexRoute } from '../pages/';

declare module '@granite-js/react-native' {
  interface RegisterScreen {
    '/about': ReturnType<typeof _AboutRoute.useParams>;
    '/analyze': ReturnType<typeof _AnalyzeRoute.useParams>;
    '/': ReturnType<typeof _IndexRoute.useParams>;
  }
}
